CREATE TABLE [dbo].[Table_1](
	[MAINT_TILTE] [nvarchar](50) NOT NULL,
	[RPRSNTV_MENU] [nvarchar](50) NOT NULL,
	[GUGUN_NM] [nvarchar](50) NOT NULL,
	[addr] [nvarchar](50) NOT NULL,
	[USAGE_DAY_WEEK_AND_TIME] [nvarchar](50) NOT NULL,
	[CNTCT_TEL] [nvarchar](50) NULL,
	[MAIN_IMG_THUMB] [nvarchar](50) NULL,
	[LNG] [int] NOT NULL,
	[LAT] [int] NOT NULL,
 CONSTRAINT [PK_Table_1] PRIMARY KEY CLUSTERED 
(
	[MAINT_TILTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


